# Makefile for Windows using MinGW

CC = g++
CFLAGS = -Wall -g -std=c++17
TARGET = proxy_server
SOURCES = proxy_parse.cpp proxy_server_with_cache.cpp
OBJECTS = $(SOURCES:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
    $(CC) $(CFLAGS) -o $@ $^

%.o: %.cpp
    $(CC) $(CFLAGS) -c $< -o $@

clean:
    rm -f $(OBJECTS) $(TARGET)

run: all
    .\$(TARGET)
