CC = g++
CFLAGS = -Wall -Wextra -std=c++11
LDFLAGS = -lws2_32

SRCS = proxy_parse.cpp proxy_server_with_cache.cpp
OBJS = $(SRCS:.cpp=.o)
TARGET = proxy_server.exe

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET) $(LDFLAGS)

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
